### ISSUE TITLE
Licensing, build & dependencies info

### ISSUE THREAD

**Issue by Symbian9** [zecruel/CadZinho#1]
Add licensing info as `LICENSE` or/and `COPYING` files. 

Also, add dependencies & build info into `README.md` or into `INSTALL.md`.

**Comment by dumblob** [comment]
- License is there.
- build info IMHO not necessarily needed - there are small readable `Makefile`s
- dependencies in Readme are redundant (`Makefile`s contain everything needed)

@Symbian9 is that sufficient?

**Comment by ghost** [comment]
> build info IMHO not necessarily needed - there are small readable `Makefile`s

As `Makefile` placed in `linux` folder, but inside `Makefile` path to source defined as `SRC_PATH=./src/` — it would not work until `Makefile` would be not be copied on one level up in folder tree.

That is why need add more info on how to compile in `README.md`.
