### ISSUE TITLE
macOS testing

### ISSUE THREAD

**Issue by tpimh** [zecruel/CadZinho#10]
With very little modification I was able to build CadZinho on macOS. I will publish my modifications soon, and invite everyone to test the resulting executable in the meantime: [CadZinho.zip](https://github.com/zecruel/CadZinho/files/7492155/CadZinho.zip).

I'm also thinking of switching the build system to CMake, so the Makefile would be uniform on Windows, Linux and macOS (I was able to build on Linux, and Windows, but Windows executable just crashes on startup), and also packaging in Flatpak for Linux. Let me know if such changes are welcome (I will do it anyway in my fork, but won't submit any pull requests if these changes are unwanted).

**Comment by zecruel** [comment]
> With very little modification I was able to build CadZinho on macOS. I will publish my modifications soon, and invite everyone to test the resulting executable in the meantime: CadZinho.zip.

Thanks for the macOS port. I will try to organize the main page, to create quick links to this and other ports.

> I'm also thinking of switching the build system to CMake, so the Makefile would be uniform on Windows, Linux and macOS (I was able to build on Linux, and Windows, but Windows executable just crashes on startup), and also packaging in Flatpak for Linux. Let me know if such changes are welcome (I will do it anyway in my fork, but won't submit any pull requests if these changes are unwanted).

Yes, improvements are always welcome!

**Comment by dumblob** [comment]
Any plans for a PR @tpimh ?

**Comment by tpimh** [comment]
Sorry, got wound up in a lot of stuff recently, please, don't expect a PR until 2022.

**Comment by tpimh** [comment]
Finally found my modified source, published here: https://github.com/tpimh/CadZinho/commit/7ed6a06d78b475d929e85d72fc27102ce8739d7e

This would only work on macOS, so the changes should be adapted to apply conditionally based on the target platform.

**Comment by tpimh** [comment]
I guess this can be closed now.
