### ISSUE TITLE
pkg-config?

### ISSUE THREAD

**Issue by zvezdochiot** [zecruel/CadZinho#11]
Hi @zecruel .

Maybe replace
https://github.com/zecruel/CadZinho/blob/bbcf4ff2efd3c71693e2ee782f7c218b65793be6/Makefile#L3-L6
to
```make
CFLAGS = -g -c
CFLAGS += -I. -I./src/ `pkg-config --cflags lua sdl2`
LDFLAGS = `pkg-config --libs lua sdl2` -lm -lGL -lGLU -lGLEW -L/usr/lib -L.
```
?

See also https://github.com/zYg-sys/CadZinho/pull/1

**Comment by zecruel** [comment]
Hi!

Thanks, it worked fine in Linux (look in the 'linux' folder in the repository).

But I couldn't get it to work on mingw (msys2)...

**Comment by zvezdochiot** [comment]
@zecruel say:
>But I couldn't get it to work on mingw (msys2)...

Maybe  replace:
https://github.com/zecruel/CadZinho/blob/f617168c093bcef39832df51f1e91c0a704fb9d1/Makefile#L4-L5
to
```make
ifeq ($(OS),Windows_NT)
LINKER_FLAGS = `sdl2-config --cflags --libs` -llua -lm -lGL -lGLU -lGLEW
INCLUDE_PATHS = -I. -I./src/ -I/usr/include/SDL2
else
LINKER_FLAGS = `pkg-config --libs lua sdl2` -lm -lGL -lGLU -lGLEW
INCLUDE_PATHS = -I. -I./src/ `pkg-config --cflags lua sdl2`
endif
```
?

See also
* https://github.com/Geo-Linux-Calculations/CadZinho/commit/e19428c0da85c76e7874338ce30001f0410db46a
* https://github.com/zYg-sys/CadZinho/pull/1
