### ISSUE TITLE
3D border?

### ISSUE THREAD

**Issue by zvezdochiot** [zecruel/CadZinho#16]
Commit https://github.com/zecruel/CadZinho/commit/ab3c2502e359c735adb8d5df4df841ddf9f831ee : 

Left boder:  
![left](https://i116.fastpic.org/big/2021/1211/39/5c9f0a4640bc63e03a43941524e35739.png)

Right border:  
![right](https://i116.fastpic.org/big/2021/1211/f9/7490c1a2e91fdda48b1d9fc8179624f9.png)

What's with the left border?

**Comment by zecruel** [comment]
Hi!

Sorry, I made a lot of changes to enable the program to 3D. This one in the repository is a test version, to verify the very basic functioning. I didn't have time to get it back to normal 2D operation. I don't expect it to have an effect so quickly.

For CadZinho to have an acceptable 3D mode, I still need to study a lot of linear algebra and OpenGL.

**Comment by zvezdochiot** [comment]
Ok.
