### ISSUE TITLE
shields?

### ISSUE THREAD

**Issue by zvezdochiot** [zecruel/CadZinho#17]
Maybe add shields in README.md?:
```md
![GitHub release (latest by date)](https://img.shields.io/github/v/release/zecruel/CadZinho)
![GitHub Release Date](https://img.shields.io/github/release-date/zecruel/CadZinho)
![GitHub repo size](https://img.shields.io/github/repo-size/zecruel/CadZinho)
![GitHub all releases](https://img.shields.io/github/downloads/zecruel/CadZinho/total)
![GitHub](https://img.shields.io/github/license/zecruel/CadZinho)
```
![GitHub release (latest by date)](https://img.shields.io/github/v/release/zecruel/CadZinho) ![GitHub Release Date](https://img.shields.io/github/release-date/zecruel/CadZinho) ![GitHub repo size](https://img.shields.io/github/repo-size/zecruel/CadZinho) ![GitHub all releases](https://img.shields.io/github/downloads/zecruel/CadZinho/total) ![GitHub](https://img.shields.io/github/license/zecruel/CadZinho)

**Comment by zecruel** [comment]
Oh, great! Thanks!
