### ISSUE TITLE
Incorrect "About" window rendering on macOS and Linux

### ISSUE THREAD

**Issue by tpimh** [zecruel/CadZinho#24]
For some reason, the window contents are stretched and nk_labels in the bottom are missing.

<img width="411" src="https://user-images.githubusercontent.com/1071872/159219740-fdc33fad-44a9-46da-b3c8-8d7a1587308d.png">
<img width="412" src="https://user-images.githubusercontent.com/1071872/159219842-a0ab6210-9c65-4dd8-a76e-349281b570bf.png">
<img width="408" src="https://user-images.githubusercontent.com/1071872/159220030-d0da5b48-1113-4ca3-b15d-30567e489e59.png">

Windows rendering is correct:
<img width="307" src="https://user-images.githubusercontent.com/1071872/159220232-e26c724d-f2e9-4b20-ba86-9f259df3d55a.png">

**Comment by zecruel** [comment]
Hi @tpimh.

It looks like the linux and macos builds were compiled with older source code, while the windows build with newer sources.

Before, this window was just like that, and later it was "beautified".

**Comment by tpimh** [comment]
Finally, got to test it. I really was on different revisions on different systems. I can confirm that this window looks identical for me after updating.
<img width="306" src="https://user-images.githubusercontent.com/1071872/161414088-3d7ab743-66b2-4756-9f7d-8578a1323f4c.png">
<img width="305" src="https://user-images.githubusercontent.com/1071872/161414119-f350eca6-62fd-48ad-85b6-4d3e3eb6c3fa.png">
<img width="305" src="https://user-images.githubusercontent.com/1071872/161414170-b42cb6c8-d85a-44ca-b399-434fe2257b37.png">
