### ISSUE TITLE
MacOS build segfaults

### ISSUE THREAD

**Issue by tpimh** [zecruel/CadZinho#25]
I haven't yet figured out the exact line or reason why my build broke, but I was able to bisect the exact commit that introduced the regression: https://github.com/zecruel/CadZinho/commit/659d7621a00752d2d18b2917eceea070330d8aa1

I will investigate the issue further and post the updates here.

**Comment by zecruel** [comment]
Hi @tpimh !

In this commit, gui.h file has changed. Try: delete all .o files previously compiled, and build entire program to update the main structs.
