### ISSUE TITLE
Use libz?

### ISSUE THREAD

**Issue by zvezdochiot** [zecruel/CadZinho#28]
Hi @zecruel .

Maybe use `-lz` for support `*.dxfz`?

**Comment by zecruel** [comment]
Hi @zvezdochiot .

Well, the project has the miniz library [(https://github.com/richgel999/miniz)](url) built in, which I think is equivalent to libz.

I particularly don't know the .dxfz format. Could you explain its purpose? Do you have an example file?

**Comment by zvezdochiot** [comment]
Hi @zecruel .

`*.dxfz` == `gzip *.dxf` (packed).

**Comment by zecruel** [comment]
In this case, it is possible to make a plugin. CadZinho has exposed zip file functions, via Lua API.

However, it is not interesting to support this file type in project. I believe it is more practical to use a system compressed file manager, since it is a regular zip file.

**Comment by zvezdochiot** [comment]
@zecruel say:
>is not interesting to support this file type in project.

Yes. Not interesting. But most of the text (XML) based projects (abiword, gnumeric,...) use this approach.

PS: The plugin will be an overhead. He's definitely unnecessary.

**Comment by zecruel** [comment]
Yes I know. By the way, we have a plugin to read XLSX files in CadZinho: [https://github.com/zecruel/CadZinho/blob/opengl/script/xlsx_lua.lua](url)
