### ISSUE TITLE
Compiled in Linux , but executable is crashing

### ISSUE THREAD

**Issue by sanliturk** [zecruel/CadZinho#3]
I have compiled the "master" in  Fedora Linux 28  : 

[s@localhost ~]$ uname -a
Linux localhost.localdomain 4.19.8-200.fc28.x86_64 #1 SMP Mon Dec 10 15:43:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[s@localhost ~]$ gcc --version
gcc (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[s@localhost ~]$ 

with the following changes : 

Makefile : 

# LINKER_FLAGS = -lSDL2main -lSDL2 -lcomdlg32 -lole32 -lmingw32 -llua
LINKER_FLAGS = -lSDL2main -lSDL2 -llua -lm
# EXE=teste9.exe
EXE=teste9.x

When the compiled program is executed , it is producing a 
"Segmentation fault" ,
crashing KDE KWin windows manager .

I have made the following change to 
config.lua :   

-- font_path = "C:\\Windows\\Fonts\\"
font_path = "/usr/share/fonts/"

It did not make any effect .

( The fonts are in different sub-directories . )

I searched "int main ..." in some possible source files , but I could find it with difficulty  .  
( It is within  interface.c ) .
Can it be made a different source file with "traditional name"    main.c ?

There are some conditional compilation statements  such as

#ifdef  __linux__

Is there a possibility to collect such words into an included file with statements such as

#define __linux__

#undef _WIN32
#undef WIN32
#undef __CYGWIN__
#undef __MINGW32__

to be able to modify them with respect to OS ?

Thank you very much .

Mehmet Erol Sanliturk

**Comment by zecruel** [comment]
Hello,

I think I found the problem: the UI font file indicated in config.lua is not present on your system, causing its variable point to an invalid address.

To make your compiled version works, just change the config.lua ui_font variable to a valid font file, or simply delete (or comment) the line, which the program will use the internal default font.

Soon I will fix the source code so that this error does not happen again. Thank you for report the error.

If you want to recompile the program, I uploaded a Makefile for linux system (I use Arch Linux): [CadZinho/linux/Makefile](url)

> I searched "int main ..." in some possible source files , but I could find it with difficulty .
> ( It is within interface.c ) .
> Can it be made a different source file with "traditional name" main.c ?

I apologize for this. I am not a professional developer and much of my programming knowledge came from self-taught. And I'm still learning. So I ask you to try to reveal some weird things, because, over time, I will make the code more readable.

This is a project that is still quite immature. Therefore, the compiled program may crash. Whenever you run it, please do inside a debugger (GDB for example) to perform a backtrace in case of error.

Best regards.

Ezequiel.

**Comment by sanliturk** [comment]
Actually "config.lua" is NOT conforming to Linux .
I have attached a modified version of it which I am using .


I have found "main" in interface.c and move it into a new source file "main.c" which it is also attached with stripped "interface.c" .

Most important trouble is in  "load_config" in "interface.c" which is not able to load font file names correctly into   "gui"  structure .

I have inserted an "exit ( 0 ) ;" at the end of "load_config" to prevent crash of KWin .

I have downloaded the "master" but I did not compile it .


My last compilation output by using the attached parts is given below :  


[s@localhost CadZinho-master]$ make -i -k
gcc -I. -I./src/ -I/usr/include/SDL2 -g -c -o obj/interface.o src/interface.c
gcc -L./lua-5.3.4/src/lib -lSDL2main -lSDL2 -llua -lm   ./obj/hershey.o  ./obj/gui_insert.o  ./obj/dxf.o  ./obj/gui_font.o  ./obj/dxf_attract.o  ./obj/gui_rect.o  ./obj/shape.o  ./obj/graph.o  ./obj/font.o  ./obj/main.o  ./obj/gui_block.o  ./obj/gui_text.o  ./obj/gui_dupli.o  ./obj/gui_hatch.o  ./obj/gui.o  ./obj/gui_lay.o  ./obj/gui_scale.o  ./obj/gui_select.o  ./obj/interface.o  ./obj/tt_graph.o  ./obj/gui_line.o  ./obj/gui_move.o  ./obj/tinyfiledialogs.o  ./obj/gui_pline.o  ./obj/gui_xy.o  ./obj/gui_circle.o  ./obj/i_svg_media.o  ./obj/list.o  ./obj/dxf_hatch.o  ./obj/bmp.o  ./obj/dxf_graph.o  ./obj/gui_info.o  ./obj/shape2.o  ./obj/dxf_create.o -lSDL2main -lSDL2 -llua -lm -o teste9.x
[s@localhost CadZinho-master]$ ./teste9.x
Width  : 1265  
Height : 950  
Font path (1) : /usr/share/fonts/  
Font path (2) : /usr/share/fonts/  
Font file name (1) : /usr/share/fonts/liberation/LiberationSans-Regular.ttf
Font file name (1) : /usr/share/fonts/google-noto/NotoSans-Regular.ttf
Font file name (1) : /usr/share/fonts/google-noto/NotoSans-Regular.ttf
UI Font path (0) : /usr/share/fonts/liberation/LiberationSans-Regular.ttf
UI Font path (1) : (null)  
UI Font path (2) : (null)  
Font height (1) : -2 
Font height (2) : 11.000000 

[s@localhost CadZinho-master]$ 
 

Please , notice that  "ui_font" string  is NOT copied properly  into "ui_font"  structure and therefore into  "gui" structure .
They are both "null" .

I do not know how to correct this part .


After correction of this part , it is possible to remove  "exit ( 0 ) ;"  and continue to testing the following parts .

**Comment by zecruel** [comment]
Hi,

Try to use config file attached. The "ui_font" variable does not a path, is a string reference to a previously loaded font (in "fonts" list variable).

You can also leave the configuration file blank, and the program will use the internal font (embedded in the code) to render the texts.

[config.lua.txt](https://github.com/zecruel/CadZinho/files/2710418/config.lua.txt)

**Comment by sanliturk** [comment]
The output is as follow when your new "config.lua" is used : 


[s@localhost CadZinho-master]$ ./teste9.x
Width  : 1265  
Height : 950  
Font path (1) : /usr/share/fonts/  
Font path (2) : /usr/share/fonts/  
Font file name (1) : /usr/share/fonts/liberation/LiberationSans-Regular.ttf
Font file name (1) : /usr/share/fonts/google-noto/NotoSans-Regular.ttf
Font file name (1) : /usr/share/fonts/google-noto/NotoSans-Regular.ttf
UI Font path (0) : LiberationSans-Regular.ttf
UI Font path (1) : LIBERATIONSANS-REGULAR.TTF  
UI Font path (2) : LIBERATIONSANS-REGULAR.TTF  
Font height (1) : -2 
Font height (2) : 11.000000 


After making   "exit ( 0 ) ;"  comment in  "load_config" : 


[s@localhost CadZinho-master]$ make -i -k
gcc -I. -I./src/ -I/usr/include/SDL2 -g -c -o obj/interface.o src/interface.c
gcc -L./lua-5.3.4/src/lib -lSDL2main -lSDL2 -llua -lm   ./obj/hershey.o  ./obj/gui_insert.o  ./obj/dxf.o  ./obj/gui_font.o  ./obj/dxf_attract.o  ./obj/gui_rect.o  ./obj/shape.o  ./obj/graph.o  ./obj/font.o  ./obj/main.o  ./obj/gui_block.o  ./obj/gui_text.o  ./obj/gui_dupli.o  ./obj/gui_hatch.o  ./obj/gui.o  ./obj/gui_lay.o  ./obj/gui_scale.o  ./obj/gui_select.o  ./obj/interface.o  ./obj/tt_graph.o  ./obj/gui_line.o  ./obj/gui_move.o  ./obj/tinyfiledialogs.o  ./obj/gui_pline.o  ./obj/gui_xy.o  ./obj/gui_circle.o  ./obj/i_svg_media.o  ./obj/list.o  ./obj/dxf_hatch.o  ./obj/bmp.o  ./obj/dxf_graph.o  ./obj/gui_info.o  ./obj/shape2.o  ./obj/dxf_create.o -lSDL2main -lSDL2 -llua -lm -o teste9.x


[s@localhost CadZinho-master]$ ./teste9.x
Width  : 1265  
Height : 950  
Font path (1) : /usr/share/fonts/  
Font path (2) : /usr/share/fonts/  
Font file name (1) : /usr/share/fonts/liberation/LiberationSans-Regular.ttf
Font file name (1) : /usr/share/fonts/google-noto/NotoSans-Regular.ttf
Font file name (1) : /usr/share/fonts/google-noto/NotoSans-Regular.ttf
UI Font path (0) : LiberationSans-Regular.ttf
UI Font path (1) : LIBERATIONSANS-REGULAR.TTF  
UI Font path (2) : LIBERATIONSANS-REGULAR.TTF  
Font height (1) : -2 
Font height (2) : 11.000000 

NEW
NEW
[s@localhost CadZinho-master]$ 




After 
Font height (2) : 11.000000 
is written , 


KWIN started to crash , and gradually recovered , and the program displayed a
window with complete menu items , but without any drawing .

The program could be stopped by selecting "Close" from left corner title bar menu .


Actually , the program is very nice .


Would you please include some test files to load and try to work on them , and , also 
some documentation about ( how to use it , file format of CAD file ) , ...  .


In Fedora Linux 28 , I could not find  "arialbd.ttf" font in  /usr/share/fonts/ directories .
It seems that it is a Microsoft font , it exists in Internet , but without any "License" information .

To prevent such mixing , you may supply two "config.lua" such as "config.lua>Windows" , "config.lua.Linux" and in OS related  "Makefile" it may be copied to "config.lua" from OS related file .



Thank you very much .

**Comment by zecruel** [comment]
The drawing format file supported is DXF, a _de facto_ industry format.

It is relatively easy to find drawing samples on the internet. For example: [http://cadkit.blogspot.com/p/sample-dxf-files.html](url).

**Comment by sanliturk** [comment]
"You can change the width and height variables in config.lua to fit in your screen."


These are the windows unrelated to the your CAD program .
Reason of such crashes , with respect to my opinion , is due to parameters related to the CAD program window handling , or a skipped step up to opening the CAD program window .

Thank you very much for link for sample DXF files .

**Comment by sanliturk** [comment]
http://cadkit.blogspot.com/p/sample-dxf-files.html
http://cadkit.blogspot.com/p/
http://cadkit.blogspot.com/

All of these are empty pages .

I think , searching

free dxf sample files

in Google will supply me some sample dxf files .

**Comment by sanliturk** [comment]
From

https://dxf1.com/


I have downloaded two files : 

https://dxf1.com/index.php/download/3-objects-signs-symbols/4277-world-map-with-parallel-and-meridians-vector-dxf-free

https://dxf1.com/index.php/download/3-objects-signs-symbols/4276-usa-map-dxf-svg-eps-ai-free-download


The CAD program successfully could be able to load and display  both of the dxf files found in the above sample files in succession and then  close the program without any crash  .


A very nice improvement would be to assign  HINTS to the menu items > When mouse position on them , its subject will be displayed .

Now , it is necessary to either study sources in very detail , or memorize them by trial and error .

**Comment by Symbian9** [comment]
@sanliturk Could you build DEB for Debian 9.x?

**Comment by sanliturk** [comment]
I do not have any Debian . I am using Fedora .

**Comment by sanliturk** [comment]
I have compiled the "master" in Fedora Linux 28 :

Within "linux" directory : 

I have deleted supplied cadzinho from ./bin/2018-12-25   .


I have modified the Makefile as given attached file .
[Makefile.txt](https://github.com/zecruel/CadZinho/files/3168850/Makefile.txt)

I have copied ../config.lua  ( into "linux" directory ) .
I have modified the config.lua 
[config.lua.txt](https://github.com/zecruel/CadZinho/files/3168856/config.lua.txt)
 as given attached file .

With the 

make -i -k 


I have compiled the program .

It started without crashing .

Hair lines are moving smoothly with cursor .
In menu items , there is no hints .



As a previous step , I have compiled it without copying the config.lua into  "linux" .
During starting , it corrupted the desktop  window , then slowly desktop window reloaded and
"cadzinho" is diplayed .  It displayed the following message :  

cannot run config. file: cannot open config.lua: No such file or directory/Packages/CAD_in_C/github.com_zecruel_CadZinho_MIT/2019_05_11/CadZinho-master/linux/
./cadzinho


With the attached "Makefile" and "config.lua" files in "linux" directory , it seems that it is starting correctly .

If config.lua in "master" directory is moved into "windows" directory and  "Makefile" in "windows" directory modified for compilation from that directory , 

and

a note attached to README.md about how to compile , users may easily compile the program "


"

Please compile the cadzinho" program from your operating system directory , either "linux" or "windows" ) by using make .

As a test file , please supply a *.dxf file of your own choice , or create a "NEW" one .

"

**Comment by zecruel** [comment]
I made a lot of updates to the code, so I think this topic has lost its purpose.
