### ISSUE TITLE
Release 0.5.0 binaries?

### ISSUE THREAD

**Issue by tpimh** [zecruel/CadZinho#43]
This commit references release 0.5.0: https://github.com/zecruel/CadZinho/commit/c4537bc14fb26f09853af95b3fd0684d29ebd314

However, the latest release available for download is 0.4.1. Was release 0.5.0 removed for some reason? Or is it just a teaser for the next release?

**Comment by zecruel** [comment]
I'm tuning CI/CD automation (GitHub actions), and a tag mark fora a draft release was created as part of the routine. Anyway, I'm preparing a new release, but it's a little later than expected.

**Comment by zecruel** [comment]
Finally: [Release 0.5.0](https://github.com/zecruel/CadZinho/releases/tag/0.5.0)
