### ISSUE TITLE
0.6.0 appimage doesn't work on Ubuntu 24.04

### ISSUE THREAD

**Issue by spagoc** [zecruel/CadZinho#50]
On Ubuntu 24.04 
CadZinho appimage  starts but the tools on the top toolbar do not work. The same in Wayland or X sessions.
The .deb  installation fails saying that it has not installable dependencies: sdl2, glew, sdl2-net.

**Comment by zecruel** [comment]
Hi,

> CadZinho appimage starts but the tools on the top toolbar do not work. The same in Wayland or X sessions.

About the problem with the AppImage, I'm trying to locate the bug. The program is not capturing the position of the moving mouse, which appears to be some incompatibility with the SDL library.

> The .deb installation fails saying that it has not installable dependencies: sdl2, glew, sdl2-net.

For installation via package manager, it is necessary to install these dependencies.

**Comment by zecruel** [comment]
Hi,

I update the [AppImage](https://github.com/zecruel/CadZinho/releases/download/0.6.0/linux_appimage.zip) in release.

Please check if it works satisfactorily.

**Comment by spagoc** [comment]
Great, now appimage works in Ubuntu 24.04.
Thanks
